version: '3.8'

services:
  catalog-api:
    build: ./CatalogService
    container_name: catalog-api
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "5001:8080"

  order-api:
    build: ./OrderService
    container_name: order-api
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "5002:8080"
    depends_on:
      - catalog-api

  gateway:
    build: ./Gateway
    container_name: yarp-gateway
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "5000:8080"
    depends_on:
      - catalog-api
      - order-api
      - seq

  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=MyStrongPassword123
    ports:
      - "5341:80"
    volumes:
      - seq-data:/data

volumes:
  seq-data:
